<?php
require absPath('app/views/core/head.phtml');
require absPath('app/views/core/header.phtml');
?>
<div>
We are
<span is="cycle-words">
    Developers
    <data data-change="4000">
        Data Scientists, System Admins, Mobile Devs, Game Devs, Tech Enthusiasts
    </data>
</span>
and
<br>
these are our Dev Stories.
</div>
<br>
[Industry Experts] [Dedicated Volunteers] [Tech Enthusiasts]
<p>
    Intro...
</p>
<?php
require absPath('app/views/core/footer.phtml');