<?php
global $Session;
?>
<header>
    <div class="column">
        <div id="logo-container">
            <a href="./">
                <object type="image/svg+xml" data="images/logo.svg">Dev Story Logo</object>
            </a>
        </div>
        <nav id="nav-container">
<?php
if (!isset($Session->loggedIn)) {
?>
            <ul id="signed-out">
                <li>
                    <a href="./join">
                        <i class="icon fas fa-user-plus"></i> Join
                    </a>
                </li>
                <li>
                    <a href="./login">
                        <i class="icon fas fa-sign-in"></i> Login
                    </a>
                </li>
            </ul>
<?php
} else {
?>
            <ul id="signed-in">
                <li>
                    <a href="./dashboard">
                        <i class="icon fas fa-home"></i> Dashboard
                    </a>
                </li>
                <li>
                    <a href="./logout">
                        <i class="icon fas fa-sign-out"></i> Logout
                    </a>
                </li>
            </ul>
<?php
}
?>
        </nav>
<?php
$sun = '';
$moon = '';
if (isset($_COOKIE['dark-mode'])) {
    if (strip_tags(trim($_COOKIE['dark-mode'])) === 'on') {
        $sun = 'visible';
    } else {
        $moon = 'visible';
    }
}
?>
        <!-- https://janessagarrow.com/blog/css-dark-mode-toggle/ -->
        <div id="dark-mode-container">
            <button is="button-toggle" id="dark-mode-toggle" data-callback="toggleDarkMode">
                <div class="off sun <?php echo $sun; ?>" data-aria="Activate light mode"></div>
                <div class="on moon <?php echo $moon; ?>" data-aria="Activate dark mode">
                    <div class="star"></div>
                    <div class="star small"></div>
                </div>
            </button>
        </div>
    </div>
</header>
<main>
<?php
readOnlyMode();
?>
    <div class="column">