<header>
    <div class="column">
        <div id="logo-container">
            <a href="./">
                <object type="image/svg+xml" data="images/logo.svg">Dev Story Logo</object>
            </a>
        </div>
        <nav id="nav-container">
            <ul id="signed-out">
                <li>
                    <a href="./join">
                        <i class="icon fas fa-user-plus"></i> Join
                    </a>
                </li>
                <li>
                    <a href="./login">
                        <i class="icon fas fa-sign-in"></i> Login
                    </a>
                </li>
            </ul>
            <!-- <ul id="signed-in">
                <li>
                    <i class="icon fas fa-cog"></i> Settings
                </li>
                <li>
                    <i class="icon fas fa-sign-out"></i> Logout
                </li>
            </ul> -->
        </nav>
        <!-- https://janessagarrow.com/blog/css-dark-mode-toggle/ -->
        <div id="dark-mode-container">
            <button is="button-toggle" id="dark-mode-toggle">
                <div class="off sun" data-aria="Activate light mode"></div>
                <div class="on moon visible" data-aria="Activate dark mode">
                    <div class="star"></div>
                    <div class="star small"></div>
                </div>
            </button>
        </div>
    </div>
</header>
<main>
    <div class="column">