<?php
$darkMode = '';
if (isset($_COOKIE['dark-mode'])) {
    $darkMode = 'data-dark-mode="' . strip_tags(trim($_COOKIE['dark-mode'])) . '"';
}
?>
<!DOCTYPE html>
<html <?php echo $darkMode; ?>>
<head>
    <title><?php __($title); ?></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/main.css">
    <script src="js/fa.min.js"></script>
    <script src="js/js.cookie.min.js"></script>
    <script src="js/elements/cycle-words.js"></script>
    <script src="js/elements/button-form.js"></script>
    <script src="js/elements/button-toggle.js"></script>
    <script src="js/main.js"></script>
</head>